// <auto-generated />
using System;
using HRApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRApp.Migrations
{
    [DbContext(typeof(HRDbContext))]
    partial class HRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("HRApp.Models.AbsenceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AbsenceRecords");
                });

            modelBuilder.Entity("HRApp.Models.AddEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntitutName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AddEducations");
                });

            modelBuilder.Entity("HRApp.Models.AdditionalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AdditionalInfos");
                });

            modelBuilder.Entity("HRApp.Models.Agreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AgreementDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AgreementEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaySystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Probation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("HRApp.Models.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("HRApp.Models.BusinessTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TripEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TripStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusinessTrips");
                });

            modelBuilder.Entity("HRApp.Models.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("HRApp.Models.CitizenshipOKIN", b =>
                {
                    b.Property<string>("OKIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OKIN");

                    b.ToTable("CitizenshipOKINs");
                });

            modelBuilder.Entity("HRApp.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Certificate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("HRApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Административно-управленческий персонал"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Отдел бухгалтерии"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Педагогический персонал"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Учебно-вспомогательный персонал"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Обслуживающий персонал"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Общежитие"
                        });
                });

            modelBuilder.Entity("HRApp.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocSerial")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("HRApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Address1Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BIK")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlaceOKATO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenshipOKIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DismissalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Index1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Index2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KPP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Korschet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomerScheta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PassportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SNILS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRApp.Models.EmployeeAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AwardDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AwardType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAwards");
                });

            modelBuilder.Entity("HRApp.Models.EmploymentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPlaceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmploymentHistories");
                });

            modelBuilder.Entity("HRApp.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasTaxBenefit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("HRApp.Models.ForeignLanguage", b =>
                {
                    b.Property<string>("OKIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OKIN");

                    b.ToTable("ForeignLanguages");
                });

            modelBuilder.Entity("HRApp.Models.IncomingDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DestinationCheck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IncomingDocuments");
                });

            modelBuilder.Entity("HRApp.Models.InternalDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SheetsNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InternalDocuments");
                });

            modelBuilder.Entity("HRApp.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OKIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OKINLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("HRApp.Models.LanguageLevel", b =>
                {
                    b.Property<string>("OKIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OKIN");

                    b.ToTable("LanguageLevels");
                });

            modelBuilder.Entity("HRApp.Models.Marriage", b =>
                {
                    b.Property<string>("OKIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarriageState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OKIN");

                    b.ToTable("Marriages");
                });

            modelBuilder.Entity("HRApp.Models.MilitaryRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountingGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Compound")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeregistrationNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MilitaryService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MillitaryOffice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecAccounting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StockCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VYS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MilitaryRegistrations");
                });

            modelBuilder.Entity("HRApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HRApp.Models.OutgoingDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SheetsNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OutgoingDocuments");
                });

            modelBuilder.Entity("HRApp.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Title = "Директор"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Title = "Заместитель директора"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Title = "Специалист по кадрам"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Title = "Специалист по охране труда"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Title = "Главный бухгалтер"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Title = "Бухгалтер"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            Title = "Экономист"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            Title = "Кассир"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            Title = "Специалист по закупкам"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 3,
                            Title = "Учитель"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 3,
                            Title = "Педагог-психолог"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 3,
                            Title = "Педагог-организатор"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            Title = "Педагог-дополнительного образования"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 3,
                            Title = "Учитель-логопед"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 3,
                            Title = "Методист"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 3,
                            Title = "Воспитатель"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 3,
                            Title = "Старший вожатый"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 4,
                            Title = "Заведующий библиотеки"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 4,
                            Title = "Библиотекарь"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 4,
                            Title = "Заведующий научной лабораторией"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 4,
                            Title = "Инженер-программист"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 4,
                            Title = "Секретарь учебной части"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 4,
                            Title = "Лаборант"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 4,
                            Title = "Медицинская сестра"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 5,
                            Title = "Водитель автомобиля"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 5,
                            Title = "Электромонтер"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 5,
                            Title = "Слесарь-сантехник"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 5,
                            Title = "Рабочий по обслуживанию зданий"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 5,
                            Title = "Вахтер"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 5,
                            Title = "Сторож"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 5,
                            Title = "Садовник"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 5,
                            Title = "Уборщик помещений"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 5,
                            Title = "Уборщик территорий"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 6,
                            Title = "Заведующий общежитием"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 6,
                            Title = "Рабочий по комплексному обслуживанию"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 6,
                            Title = "Вахтер"
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 6,
                            Title = "Сторож"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 6,
                            Title = "Уборщик помещений"
                        });
                });

            modelBuilder.Entity("HRApp.Models.Privilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Privileges");
                });

            modelBuilder.Entity("HRApp.Models.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Main")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfessionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("HRApp.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("HRApp.Models.QualificationTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Institut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QualificationTrainings");
                });

            modelBuilder.Entity("HRApp.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoginUser = "Admin",
                            PasswordUser = "admin"
                        });
                });

            modelBuilder.Entity("HRApp.Models.RegisterDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegisterDocuments");
                });

            modelBuilder.Entity("HRApp.Models.Retraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Retrainings");
                });

            modelBuilder.Entity("HRApp.Models.SalaryRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("SalaryRates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100000m,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 60000m,
                            PositionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 65000m,
                            PositionId = 3
                        });
                });

            modelBuilder.Entity("HRApp.Models.SickLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedStateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SickLeaves");
                });

            modelBuilder.Entity("HRApp.Models.SocialBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SocialBenefits");
                });

            modelBuilder.Entity("HRApp.Models.TimeSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HourPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursWeek1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoursWeek2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeSheetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("HRApp.Models.TimeSheetCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSheetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TimeSheetCalendars");
                });

            modelBuilder.Entity("HRApp.Models.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CalendarDaysNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VacationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("HRApp.Models.AbsenceRecord", b =>
                {
                    b.HasOne("HRApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRApp.Models.Award", b =>
                {
                    b.HasOne("HRApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRApp.Models.Course", b =>
                {
                    b.HasOne("HRApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRApp.Models.Employee", b =>
                {
                    b.HasOne("HRApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRApp.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HRApp.Models.EmployeeAward", b =>
                {
                    b.HasOne("HRApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRApp.Models.Position", b =>
                {
                    b.HasOne("HRApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRApp.Models.SalaryRate", b =>
                {
                    b.HasOne("HRApp.Models.Position", "Position")
                        .WithMany("SalaryRates")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HRApp.Models.SocialBenefit", b =>
                {
                    b.HasOne("HRApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRApp.Models.Position", b =>
                {
                    b.Navigation("SalaryRates");
                });
#pragma warning restore 612, 618
        }
    }
}
